name: example
description: The example application for Rikimaru projects&#x27;s group

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  architecture_component:
    path: ../architecture_component

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0

  architecture_generator:
    path: ../architecture_generator

flutter:
  uses-material-design: true
