name: example
description: The example application for Rikimaru projects&#x27;s group

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  architecture_component: '>=0.0.1 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  architecture_generator: '>=0.0.1 <1.0.0'
  build_runner: ^1.0.0
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  architecture_component:
    path: ../architecture_component

dev_dependency_overrides:
  architecture_generator:
    path: ../architecture_generator
